### Logistic Training on features given by botornot

In [4]:
from sklearn import linear_model
import pandas as pd
import numpy as np


In [24]:
df = pd.read_csv('training_set_1_filter.csv',encoding = "ISO-8859-1")
print(df.tail(5))
print(df.shape)

      index            id        id_str     screen_name  \
2662    609  5.141790e+07  5.141790e+07  thedreamstream   
2663    820  7.460000e+17  7.460000e+17    ismail_abaid   
2664    583  3.044051e+08  3.044051e+08     othello3579   
2665    391  4.178444e+07  4.178444e+07   AllTheCheeses   
2666    404  7.510000e+17  7.510000e+17       xbangtan1   

                              location  \
2662           IN UR HEAD WHEN U SLEEP   
2663                           Morocco   
2664                               NaN   
2665                               NaN   
2666  äó_¥Ÿdont follow this accäó_¥Ÿ   

                                            description  \
2662  So we all love hearing about other ppls dreams...   
2663                                                NaN   
2664                                                NaN   
2665                                                NaN   
2666  Giving you a free follow and you can help me b...   

                          url  follow

In [25]:
df1 = np.matrix(df.loc[:,'BotOrNot':'user_classification'])
print(df1.shape)
y = df.is_bot
print(y.shape)

(2667, 7)

In [38]:
from sklearn.model_selection import cross_val_predict
from sklearn.linear_model import LogisticRegression,LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=25)
train_list = df1
target_list = y
accuracy = cross_val_score(clf, train_list, target_list, cv=10, scoring='accuracy')
precision = cross_val_score(clf, train_list, target_list, cv=10, scoring='precision')
print ("cmean accuracy = %6.4f"%np.mean(accuracy))
print ("mean precision = %6.4f"%np.mean(precision))

cmean accuracy = 0.7261
mean precision = 0.7313


In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    df1, y, stratify=y, random_state=42)

In [36]:
logreg01 = LogisticRegression(penalty='l2',C=100).fit(X_train, y_train)

print("Training set score: {:.3f}".format(logreg01.score(X_train, y_train)))
print("Test set score: {:.3f}".format(logreg01.score(X_test, y_test)))

from sklearn.metrics import confusion_matrix
y_pred = logreg01.predict(X_test)
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

Training set score: 0.842
Test set score: 0.816
[[285  70]
 [ 53 259]]
             precision    recall  f1-score   support

          0       0.84      0.80      0.82       355
          1       0.79      0.83      0.81       312

avg / total       0.82      0.82      0.82       667



In [40]:
rf1 = clf.fit(X_train, y_train)

print("Training set score: {:.3f}".format(rf1.score(X_train, y_train)))
print("Test set score: {:.3f}".format(rf1.score(X_test, y_test)))

from sklearn.metrics import confusion_matrix
y_pred = rf1.predict(X_test)
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

Training set score: 0.998
Test set score: 0.801
[[273  82]
 [ 51 261]]
             precision    recall  f1-score   support

          0       0.84      0.77      0.80       355
          1       0.76      0.84      0.80       312

avg / total       0.80      0.80      0.80       667



In [47]:
from sklearn.model_selection import cross_val_score
from sklearn.datasets import make_blobs
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier

X = df1
y = df.is_bot
# X, y = make_blobs(n_samples=10000, n_features=10, centers=100,
#     random_state=0)
clf = DecisionTreeClassifier(max_depth=None, min_samples_split=2,
    random_state=0)
scores = cross_val_score(clf, X, y)
print(scores.mean())


clf = RandomForestClassifier(n_estimators=100, max_depth=None,
     random_state=0)
scores = cross_val_score(clf, X, y)
print(scores.mean())


clf = ExtraTreesClassifier(n_estimators=100, max_depth=None,
     random_state=0)
scores = cross_val_score(clf, X, y)
print(scores)
scores.mean() > 0.999

0.391451068616
0.503937007874
[ 0.60404949  0.75478065  0.51068616]


False

In [45]:
df1.shape

(2667, 7)

# BackUp

In [1]:
print(__doc__)

from sklearn import datasets, neighbors, linear_model

digits = datasets.load_digits()
X_digits = digits.data
y_digits = digits.target

n_samples = len(X_digits)

X_train = X_digits[:.9 * n_samples]
y_train = y_digits[:.9 * n_samples]
X_test = X_digits[.9 * n_samples:]
y_test = y_digits[.9 * n_samples:]

knn = neighbors.KNeighborsClassifier()
logistic = linear_model.LogisticRegression()

print('KNN score: %f' % knn.fit(X_train, y_train).score(X_test, y_test))
print('LogisticRegression score: %f'
      % logistic.fit(X_train, y_train).score(X_test, y_test))

Automatically created module for IPython interactive environment


/Users/alvin/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:11: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
/Users/alvin/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:12: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
/Users/alvin/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:13: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
/Users/alvin/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:14: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


KNN score: 0.961111
LogisticRegression score: 0.938889


In [2]:
y_digits = digits.target

In [3]:
y_digits

array([0, 1, 2, ..., 8, 9, 8])

In [4]:
X_digits

array([[  0.,   0.,   5., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,  10.,   0.,   0.],
       [  0.,   0.,   0., ...,  16.,   9.,   0.],
       ..., 
       [  0.,   0.,   1., ...,   6.,   0.,   0.],
       [  0.,   0.,   2., ...,  12.,   0.,   0.],
       [  0.,   0.,  10., ...,  12.,   1.,   0.]])

In [48]:
XX, yy = make_blobs(n_samples=10000, n_features=10, centers=100,
    random_state=0)

In [57]:
X

matrix([[ 0.08      ,  0.37      ,  0.01      , ...,  0.02      ,
          0.47      ,  0.        ],
        [ 0.1       ,  0.4       ,  0.01      , ...,  0.07      ,
          0.16      ,  0.        ],
        [ 0.11      ,  0.32      ,  0.04      , ...,  0.03      ,
          0.11      ,  0.        ],
        ..., 
        [ 0.98      ,  0.92      ,  0.79314713, ...,  0.81666667,
          0.8       ,  0.97      ],
        [ 0.79      ,  0.62      ,  0.79314713, ...,  0.5925    ,
          0.51666667,  0.97066667],
        [ 0.96      ,  0.905     ,  0.79314713, ...,  0.87      ,
          0.88      ,  0.98      ]])

In [58]:
X.shape

(2667, 7)

In [51]:
print (yy)

[85 64 93 ..., 98 80 91]


In [59]:
y.shape

(2667,)